### ISSUE TITLE
Can't call parseJSONValue with rvalues

### ISSUE THREAD

**Issue by dhasenan** [s-ludwig/std_data_json#23] opened 2016-03-25 16:04 UTC
```D
auto val = `{"hello": "world"}`.parseJSONValue;
```

This yields the following error:
```
lib/couch.d(14,35): Error: template stdx.data.json.parser.parseJSONValue cannot deduce function from argument types !()(string), candidates are:
../../.dub/packages/std_data_json-0.18.1/source/stdx/data/json/parser.d(119,11):        stdx.data.json.parser.parseJSONValue(LexOptions options = Lex
Options.init, Input)(ref Input input, string filename = "") if (isInputRange!Input && (isSomeChar!(ElementType!Input) || isIntegral!(ElementType!Inpu
t)))
../../.dub/packages/std_data_json-0.18.1/source/stdx/data/json/parser.d(164,17):        stdx.data.json.parser.parseJSONValue(Input)(ref Input tokens) if (isJSONTokenInputRange!Input)
```

Looks like string literals are not lvalues and cannot be taken by reference. You can sidestep this by assigning the string literal to a variable and then calling `parseJSONValue`, so it's not a huge issue, but it will trip people up when they're first trying to use std.data.json.

**Comment by dhasenan** [comment] 2016-03-25 16:11
Silly me, it's anything that isn't an lvalue. So you have a nice one-liner like:

```D
JSONValue getWeather()
{
    return parseJSONValue(std.net.curl.get("http://example.net/weatherService"));
}
```

Doesn't work.

**Comment by s-ludwig** [comment] 2016-03-25 18:41
Duplicate of #14. The right function is `toJSONValue` in correspondence with `to`/`parse` in `std.conv`.

**Closed by s-ludwig** 2016-03-25 18:41 UTC
